module.exports = {
  extends: [
    'stylelint-config-standard',
    'stylelint-config-tailwindcss',
  ],
  plugins: ['stylelint-order'],
  rules: {
    // 自定义规则
    'order/properties-order': [
      'position',
      'top',
      'right',
      'bottom',
      'left',
      'z-index',
      'display',
      'flex-direction',
      'justify-content',
      'align-items',
      'flex',
      'flex-wrap',
      'flex-shrink',
      'flex-grow',
      'flex-basis',
      'grid',
      'grid-template-columns',
      'grid-template-rows',
      'grid-column',
      'grid-row',
      'grid-gap',
      'gap',
      'float',
      'width',
      'min-width',
      'max-width',
      'height',
      'min-height',
      'max-height',
      'padding',
      'padding-top',
      'padding-right',
      'padding-bottom',
      'padding-left',
      'margin',
      'margin-top',
      'margin-right',
      'margin-bottom',
      'margin-left',
      'overflow',
      'overflow-x',
      'overflow-y',
      'border',
      'border-top',
      'border-right',
      'border-bottom',
      'border-left',
      'border-width',
      'border-style',
      'border-color',
      'border-radius',
      'background',
      'background-color',
      'background-image',
      'background-repeat',
      'background-position',
      'background-size',
      'color',
      'font-size',
      'font-family',
      'font-weight',
      'line-height',
      'text-align',
      'text-decoration',
      'text-transform',
      'text-shadow',
      'vertical-align',
      'opacity',
      'visibility',
      'transition',
      'transition-property',
      'transition-duration',
      'transition-timing-function',
      'transition-delay',
      'transform',
      'animation',
      'box-shadow',
      'cursor',
      'user-select',
    ],
    'declaration-empty-line-before': null,
    'rule-empty-line-before': null,
    'selector-pseudo-class-no-unknown': [
      true,
      {
        ignorePseudoClasses: ['global', 'local'],
      },
    ],
  },
  ignoreFiles: ['node_modules/**/*', 'dist/**/*', 'build/**/*'],
}